# Mongo Events Demo - Homelab Integration
# Port 8140 - chrislawrence.ca/events

services:
  mongo-events:
    build: .
    container_name: mongo-events
    restart: unless-stopped
    networks:
      - web
    ports:
      - "8140:5000"
    environment:
      - FLASK_ENV=production
      - MONGODB_URI=mongodb+srv://chrislawrencedev:Xc93FPujnvVD2Xb6@eventsphere.mzturli.mongodb.net/?retryWrites=true&w=majority&appName=EventSphere
      - MONGODB_DB_NAME=EventSphere
      - PORT=5000
      - HOST=0.0.0.0  # Override the .env file setting
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


networks:
  web:
    external: true
    name: homelab-web
