# Mongo Events Demo - Local Development
# Port 5000 - localhost:5000

services:
  mongo-events:
    build: .
    container_name: mongo-events
    restart: unless-stopped
    networks:
      - mongo-events-network
    ports:
      - "5000:5000"
    depends_on:
      mongo-events-db:
        condition: service_healthy
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongo-events-db:27017/eventsphere
      - PORT=5000
      - HOST=0.0.0.0
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo-events-db:
    image: mongo:7
    container_name: mongo-events-db
    restart: unless-stopped
    networks:
      - mongo-events-network
    volumes:
      - mongo_events_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=eventsphere
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mongo-events-network:
    driver: bridge

volumes:
  mongo_events_data:
